### ISSUE TITLE
Entering email with invalid IP adress to get badge

### ISSUE THREAD

**Issue by kalalsherif** [assistx/openbadges#9] opened 2013-03-14 17:47 UTC
Environment - 
 Safari, Win 8

Priority - 3

Severity - 3

Description and Customer Impact - 
 When trying to register to http://msobitest.azurewebsites.net/ the client could enter an invalid email address by error and go trough the process without knowing it.

Repro Steps - 
 -Navigate to http://msobitest.azurewebsites.net/
 -Type an email address with an invalid IP. (Ex. tester@1234.1234.1234, tester@123.123)

Results - 
•Its allowed as a valid email address

Expected - 
•It should show "Contact must be a valid email address if supplied"

**Comment by lilian-wang** [comment] 2013-03-16 16:27
Duplicate of Issue https://github.com/assistx/openbadges/issues/6

**Comment by msousley** [comment] 2013-04-16 21:39
https://github.com/assistx/openbadges_testsite/commit/ef2dadccd2021d4c91da89429fc52465ecea4924

**Closed as completed by msousley** 2013-04-16 21:39 UTC
