### ISSUE TITLE
Badges being claimed are lost when user clicks on the "I am not X@Y" button

### ISSUE THREAD

**Issue by ru2dvs** [assistx/openbadges#40] opened 2013-03-14 18:34 UTC
○ How Found - "Microsoft New SDET Bug Bash"
○ Priority - 1
○ Severity - 2

○ Description and Customer Impact

Client: Firefox 19.0.2

Even if a user decides to supply different credentials (due to a previously logged in user/user error), they probably still want the badge.  Currently, after clicking on the "I am not X@Y" button, the badge being claimed is lost.

○ Repro:
1. Go to http://msobitest.azurewebsites.net/
2. Obtain the badge using Azure ACS, but do not confirm your identity (detailed steps below):
   a. Input any email and hit "Get Your Open Badge"
   b. If prompted, click on the "Sign in with Azure ACS"
   c. If prompted, select any OpenId provider
   d. If prompted, log into OpenId provider with valid credentials
3. Click on the "I am not X@Y.com" Button

○ Results

![desk](https://f.cloud.github.com/assets/3856681/260513/a5673b06-8cd7-11e2-8aa0-66419f7fcd41.png)

The badges are lost.

○ Expected

You should still be claiming the same badge.

**Comment by lilian-wang** [comment] 2013-03-16 16:15
Duplicate of Issue https://github.com/assistx/openbadges/issues/19

**Closed as completed** 2013-04-08 22:13 UTC
Labels: bug
