### ISSUE TITLE
Cannot Upload Badges in Firefox

### ISSUE THREAD

**Issue by benkur** [assistx/openbadges#43] opened 2013-03-14 18:40 UTC
Environment: Firefox v19.0.2

How Found - Microsoft New SDET Bug Bash
 Priority - 2
 Severity - 2

Description and Customer Impact -
Badges cannot be uploaded from Firefox at all.

Repro Steps -
Upload a badge using Firefox ( we had version 19.0.2).  This is happening 100% of the time for me in Firefox.

Result - 
Error that says: "This seems to be an invalid url (or there was a DNS error): "

Expected - 
Badge upload accepted.

**Comment by lilian-wang** [comment] 2013-03-16 16:11
Duplicate of Issue https://github.com/assistx/openbadges/issues/22

**Comment by msousley** [comment] 2013-04-08 17:19
Only actual badges can be uploaded.  Error description has been updated in v1.0 to say the badge does not have the baked in parts

**Closed as completed by msousley** 2013-04-08 17:19 UTC
Labels: bug
