### ISSUE TITLE
Account used for OpenId is not signed out after user selects the "I am not X@Y.com" option

### ISSUE THREAD

**Issue by ru2dvs** [assistx/openbadges#30] opened 2013-03-14 18:17 UTC
○ How Found - "Microsoft New SDET Bug Bash"
○ Priority - 1
○ Severity - 3

○ Description and Customer Impact

Client: Firefox 19.0.2

The expected action after indicating that "I am not User X" is that you are logged out and given a chance to supply new credentials.  Because we do not log users out:
1. Users attempting to log on again using the same openid provider do not have a chance to supply new credentials
2. User may expect to be logged out of openid provider, but is not actually logged out.

○ Repro:
1. Sign in to any of the openId providers (Live/Google/Facebook/Yahoo), either through the site or externally.
2. Go to http://msobitest.azurewebsites.net/
3. Input any email and hit "Get Your Open Badge"
4. If prompted, click on the "Sign in with Azure ACS"
5. If prompted, select the OpenId Provider you signed in with in step 1
6. Click on the "I am not X@Y.com"
7. Repeat steps 2 - 5

○ Results

The service attempts to give the badge to the same openId, even though the user has previously indicated that they are not that user.

○ Expected

You should have a chance to sign in using a new username/password for the openId provider.

Alternatively, once you say "I am not X@Y.com", indicate to the user that they must sign out of the openId provider manually.

**Comment by lilian-wang** [comment] 2013-03-16 16:17
Duplicate of Issue https://github.com/assistx/openbadges/issues/18

**Comment by msousley** [comment] 2013-04-08 20:37
closed the issue in b7ee75f just now

**Closed as completed by msousley** 2013-04-08 20:37 UTC
Labels: duplicate
