### ISSUE TITLE
On clicking "Get Your Open Badge" without entering any email id, an exception is thrown

### ISSUE THREAD

**Issue by swapnilsc** [assistx/openbadges#15] opened 2013-03-14 17:55 UTC
Environment - Safari 5.1.7 browser
How Found - Microsoft New SDET Bug Bash
Priority - 2
Severity - 2
Description and Customer Impact - When "Get Your Open Badge" is clicked without entering any email id in the text field following exception is thrown -
"Exception - System.Net.WebException: The remote server returned an error: (500) Internal Server Error. at System.Net.HttpWebRequest.GetResponse() at _Default.createAssertion()
at System.Net.HttpWebRequest.GetResponse() at _Default.createAssertion()"

Repro Steps - 
- Navigate to the Microsoft open badges page - http://msobitest.azurewebsites.net/
- Click on "Get Your Open Badge" without entering anything in the email field.
  Results - Exception is thrown.
  Expected - A proper error message should be shown when no email id is entered.

![No email error](https://f.cloud.github.com/assets/3849509/260228/9784c086-8cd1-11e2-9bea-4e82b72b1a5c.PNG)

**Comment by lilian-wang** [comment] 2013-03-16 16:22
Duplicate of Issue https://github.com/assistx/openbadges/issues/13

**Closed as completed** 2013-04-17 20:32 UTC
