### ISSUE TITLE
Sign-out Does Not Correctly Remove Session Cookies

### ISSUE THREAD

**Issue by benkur** [assistx/openbadges#47] opened 2013-03-14 18:47 UTC
Environment: Any browser.

How Found - Microsoft New SDET Bug Bash
Priority - 2
Severity - 2

Description and Customer Impact -
 The Sign-out function does not correctly delete the Session cookies.  This can cause the user to incorrectly think that they have been signed out when in fact they are still logged in.

Repro Steps -
Using Firefox and the Web Developer plug-in, log in to the site.  Click "View Cookies" from WebDev toolbar.  Click Sign-out.  Now check "View Cookies" again and see that nothing has changed.

Result - 
It is still possible to relogin without having to provide credentials.  This is not what "sign out" means in web application conventions.

Expected - 
All session cookies should be deleted when the user clicks Sign Out.

**Comment by msousley** [comment] 2013-04-08 17:37
Duplicate of Issue #18

**Comment by msousley** [comment] 2013-04-08 20:37
closed the issue in b7ee75f just now

**Closed as completed by msousley** 2013-04-08 20:37 UTC
Labels: duplicate
