### ISSUE TITLE
Unable to signout of gmail account

### ISSUE THREAD

**Issue by deesha** [assistx/openbadges#33] opened 2013-03-14 18:23 UTC
Environment: Google Chrome

Severity: 1 
Priority: 1

Repro Steps:
1. Login to gmail
2. Then Sign out
3. Then select the Sign in with Azure and select gmail
4. It directly signs in and shows the file upload page 

Expected: To show the gmail sign in page

**Comment by ru2dvs** [comment] 2013-03-14 18:28
Seems like a repeat of Issue #30.  Updated #30 to indicate that issue is reproed in Chrome

**Comment by deesha** [comment] 2013-03-14 18:35
It is a different issue where I am clicking on the sign out button but still it is logged in, not on the "I am not .." option.

**Comment by ru2dvs** [comment] 2013-03-14 18:37
Ah I see.  My bad and thank you for the explanation!

**Comment by msousley** [comment] 2013-04-08 17:37
Duplicate of Issue #18

**Comment by msousley** [comment] 2013-04-08 20:37
closed the issue in b7ee75f just now

**Closed as completed by msousley** 2013-04-08 20:37 UTC
Labels: duplicate
